
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;

using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BO
{
	/// <summary>
	/// The ScheduledRouteTemplate extensions
	/// </summary>
	public static class ScheduledRouteTemplateExtensions
	{
        public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> GetTemplatesRA(){using (new zAppDev.DotNet.Framework.Profiling.Profiler("ScheduledRouteTemplate", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "GetTemplatesRA")) {
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> templates = new System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>();
DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser user = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser>((x) => x.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
if ((user != null)) {
var _var0 = user?.RegionalAgent?.Id;templates = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>((x) => x.Owner.Id == _var0).ToList();}
return templates;
}
}


public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> GetAvailableRATemplates(){using (new zAppDev.DotNet.Framework.Profiling.Profiler("ScheduledRouteTemplate", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "GetAvailableRATemplates")) {
DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser currentUser = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser>((x) => x.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> templates = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>((x) => x.IsPrivate == false && x.Owner != null);
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> temp = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>((x) => x.IsPrivate == true && x.Owner != null);
foreach (var templ in temp ?? Enumerable.Empty<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>()) {
if (((templ?.IsPrivate ?? false) && (templ?.VisibleTo?.Contains(currentUser?.LSP) ?? false))) {
templates?.Add(templ);
}
}
return templates;
}
}


public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> GetTemplatesFromLSP(){using (new zAppDev.DotNet.Framework.Profiling.Profiler("ScheduledRouteTemplate", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "GetTemplatesFromLSP")) {
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> templates = new System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>();
DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser user = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser>((x) => x.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
if ((user != null)) {
var _var1 = user?.LSP?.Id;templates = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>((x) => x.OwnerLSP.Id == _var1).ToList();}
return templates;
}
}


public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> GetAvailableLSPTemplates(){using (new zAppDev.DotNet.Framework.Profiling.Profiler("ScheduledRouteTemplate", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "GetAvailableLSPTemplates")) {
DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser currentUser = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser>((x) => x.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> templates = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>((x) => x.IsPrivate == false && x.OwnerLSP != null);
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate> temp = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>((x) => x.IsPrivate == true && x.Owner != null);
foreach (var templ in temp ?? Enumerable.Empty<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>()) {
if (((templ?.IsPrivate ?? false) && (templ?.VisibleToRAs?.Contains(currentUser?.RegionalAgent) ?? false))) {
templates?.Add(templ);
}
}
return templates;
}
}



        
	}
}
