
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;

using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BO
{
	/// <summary>
	/// The WorkContract extensions
	/// </summary>
	public static class WorkContractExtensions
	{
        public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkContract> GetMyWorkContracts(){using (new zAppDev.DotNet.Framework.Profiling.Profiler("WorkContract", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "GetMyWorkContracts")) {
System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkContract> contracts = new System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkContract>();
if (((zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentApplicationUser()?.IsInRole("LSPAdmin") ?? false) || (zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentApplicationUser()?.IsInRole("LSPUser") ?? false))) {
DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser thisuser = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser>((x) => x.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
var _var0 = thisuser?.LSP?.Id;contracts = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkContract>((x) => x.LSP.Id == _var0).ToList();return contracts;
}
else if (((zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentApplicationUser()?.IsInRole("RAAdmin") ?? false) || (zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentApplicationUser()?.IsInRole("RAUser") ?? false))) {
DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser thisuser = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser>((x) => x.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
var _var1 = thisuser?.RegionalAgent?.Id;contracts = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkContract>((x) => x.RegionalAgent.Id == _var1).ToList();return contracts;
}
else {
return contracts;
}
}
}



        
	}
}
