// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS3_LogisticsPoolingForUrbanDistribution;
(function (DSS3_LogisticsPoolingForUrbanDistribution) {
    var Services;
    (function (Services) {
        /**
         * Client for 'KPIInit' Service
         */
        var KPIInitServiceClient = (function () {
            function KPIInitServiceClient() {
            }
            /**
            *
            */
            KPIInitServiceClient.InitKPIs = function () {
                var _data = { params: {} };
                return axios.get(window._context.siteRoot + KPIInitServiceClient.baseUrl + "InitKPIs", _data);
            };
            return KPIInitServiceClient;
        }());
        /**
         * Base url for 'KPIInit' Service
         */
        KPIInitServiceClient.baseUrl = "/api/KPIInit/";
        Services.KPIInitServiceClient = KPIInitServiceClient;
    })(Services = DSS3_LogisticsPoolingForUrbanDistribution.Services || (DSS3_LogisticsPoolingForUrbanDistribution.Services = {}));
})(DSS3_LogisticsPoolingForUrbanDistribution || (DSS3_LogisticsPoolingForUrbanDistribution = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.KPIInit = DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIInitServiceClient;
