// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var DSS3_LogisticsPoolingForUrbanDistribution;
(function (DSS3_LogisticsPoolingForUrbanDistribution) {
    var Services;
    (function (Services) {
        /**
         * Client for 'KPIService' Service
         */
        var KPIServiceServiceClient = (function () {
            function KPIServiceServiceClient() {
            }
            /**
            *
            */
            KPIServiceServiceClient.GetVolumePerLSP = function (Name) {
                var _data = { params: { Name: Name } };
                return axios.get(window._context.siteRoot + KPIServiceServiceClient.baseUrl + "GetVolumePerLSP", _data);
            };
            /**
            *
            */
            KPIServiceServiceClient.GetVolumePerUnit = function (Name) {
                var _data = { params: { Name: Name } };
                return axios.get(window._context.siteRoot + KPIServiceServiceClient.baseUrl + "GetVolumePerUnit", _data);
            };
            /**
            *
            */
            KPIServiceServiceClient.CO2PerCarrier = function (Name) {
                var _data = { params: { Name: Name } };
                return axios.get(window._context.siteRoot + KPIServiceServiceClient.baseUrl + "CO2PerCarrier", _data);
            };
            return KPIServiceServiceClient;
        }());
        /**
         * Base url for 'KPIService' Service
         */
        KPIServiceServiceClient.baseUrl = "/api/KPIService/";
        Services.KPIServiceServiceClient = KPIServiceServiceClient;
    })(Services = DSS3_LogisticsPoolingForUrbanDistribution.Services || (DSS3_LogisticsPoolingForUrbanDistribution.Services = {}));
})(DSS3_LogisticsPoolingForUrbanDistribution || (DSS3_LogisticsPoolingForUrbanDistribution = {}));
// Create service shortcut
if (window.$api == null) {
    window.$api = {};
}
window.$api.KPIService = DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIServiceServiceClient;
