// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for ApplicationClientTest and is intended
    ///to contain all ApplicationClientTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("ApplicationClient Repository Tests")]
    [Category("ApplicationClient Repository Tests")]
    internal class ApplicationClientTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `ApplicationClient`")]
        [Order(0)]
        public void ApplicationClient_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _applicationsystembo_user_clients = new zAppDev.DotNet.Framework.Identity.Model.ApplicationUser
            {
                UserName = "1eabd5ec-e283-431c-b727-ca431a607a33ApplicationUser_UserName",
                PasswordHash = "ApplicationUser_PasswordHash",
                SecurityStamp = "ApplicationUser_SecurityStamp",
                EmailConfirmed = true,
                LockoutEnabled = true,
                PhoneNumberConfirmed = true,
                TwoFactorEnabled = true,
                AccessFailedCount = 5673,
                Name = "ApplicationUser_Name",
                Email = "ApplicationUser_Email",
                PhoneNumber = "ApplicationUser_PhoneNumber",
                LockoutEndDate = now,
            };
            new PersistenceSpecification<zAppDev.DotNet.Framework.Identity.Model.ApplicationClient>(Session)
            .CheckProperty(p => p.ClientKey, "ApplicationClient_ClientKey")
            .CheckProperty(p => p.IPAddress, "ApplicationClient_IPAddress")
            .CheckProperty(p => p.SessionId, "ApplicationClient_SessionId")
            .CheckProperty(p => p.ConnectedOn, now)
            .CheckReference(p => p.User, _applicationsystembo_user_clients)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `ApplicationClient`")]
        [Order(1)]
        public void ApplicationClient_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<zAppDev.DotNet.Framework.Identity.Model.ApplicationClient> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<zAppDev.DotNet.Framework.Identity.Model.ApplicationClient>(
                              a => true
                              && (a.ClientKey != string.Empty && a.ClientKey != null)
                              && (a.IPAddress != string.Empty && a.IPAddress != null)
                              && (a.SessionId != string.Empty && a.SessionId != null)
                              && a.ConnectedOn.GetValueOrDefault().Date <= DateTime.UtcNow.Date
                              && a.User != null
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}