// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for CommentTest and is intended
    ///to contain all CommentTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("Comment Repository Tests")]
    [Category("Comment Repository Tests")]
    internal class CommentTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `Comment`")]
        [Order(0)]
        public void Comment_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.Comment>(Session)
            .CheckProperty(p => p.Message, "Comment_Message")
            .CheckProperty(p => p.IssueDate, now)
            .CheckProperty(p => p.RefRevision, 2094)
            .CheckProperty(p => p.RefGUID, "Comment_RefGUID")
            .CheckProperty(p => p.Issuer, "Comment_Issuer")
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `Comment`")]
        [Order(1)]
        public void Comment_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.Comment> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.Comment>(
                              a => true
                              && (a.Message != string.Empty && a.Message != null)
                              && a.IssueDate.GetValueOrDefault().Date <= DateTime.UtcNow.Date
                              && (a.RefRevision + 123 > 0)
                              && (a.RefGUID != string.Empty && a.RefGUID != null)
                              && (a.Issuer != string.Empty && a.Issuer != null)
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}