// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for CustomVolumeTest and is intended
    ///to contain all CustomVolumeTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("CustomVolume Repository Tests")]
    [Category("CustomVolume Repository Tests")]
    internal class CustomVolumeTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `CustomVolume`")]
        [Order(0)]
        public void CustomVolume_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _volumebo_volumecomposition_customvolume = new DSS3_LogisticsPoolingForUrbanDistribution.BO.VolumeComposition
            {
                Units = 5905,
            };
            var _volumebo_volumecomposition_customvolume2 = new DSS3_LogisticsPoolingForUrbanDistribution.BO.VolumeComposition
            {
                Units = 8032,
            };
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.CustomVolume>(Session)
            .CheckProperty(p => p.Weight, 222222.22M)
            .CheckBag(p => p.VolumeComposition, (new List<DSS3_LogisticsPoolingForUrbanDistribution.BO.VolumeComposition>
            {
                _volumebo_volumecomposition_customvolume,
                _volumebo_volumecomposition_customvolume2
            }))
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `CustomVolume`")]
        [Order(1)]
        public void CustomVolume_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.CustomVolume> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.CustomVolume>(
                              a => true
                              && (a.Weight + 123 > 0)
                              && a.VolumeComposition.Any()
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}