// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for LegVolumeDetailsTest and is intended
    ///to contain all LegVolumeDetailsTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("LegVolumeDetails Repository Tests")]
    [Category("LegVolumeDetails Repository Tests")]
    internal class LegVolumeDetailsTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `LegVolumeDetails`")]
        [Order(0)]
        public void LegVolumeDetails_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _utilsbo_origin_legvolumedetails = new DSS3_LogisticsPoolingForUrbanDistribution.BO.Location
            {
                Name = "Location_Name",
                Street = "Location_Street",
                City = "Location_City",
                Country = "Location_Country",
                Number = "Location_Number",
                PostCode = "Location_PostCode",
                Label = "Location_Label",
            };
            var _utilsbo_destination_legvolumedetails_1 = new DSS3_LogisticsPoolingForUrbanDistribution.BO.Location
            {
                Name = "Location_Name",
                Street = "Location_Street",
                City = "Location_City",
                Country = "Location_Country",
                Number = "Location_Number",
                PostCode = "Location_PostCode",
                Label = "Location_Label",
            };
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.LegVolumeDetails>(Session)
            .CheckProperty(p => p.FreeSpace, 222222.22M)
            .CheckProperty(p => p.Time, "LegVolumeDetails_Time")
            .CheckProperty(p => p.Distance, 7183)
            .CheckProperty(p => p.CurrentLoad, 222222.22M)
            .CheckReference(p => p.Origin, _utilsbo_origin_legvolumedetails)
            .CheckReference(p => p.Destination, _utilsbo_destination_legvolumedetails_1)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `LegVolumeDetails`")]
        [Order(1)]
        public void LegVolumeDetails_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.LegVolumeDetails> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.LegVolumeDetails>(
                              a => true
                              && (a.FreeSpace + 123 > 0)
                              && (a.Time != string.Empty && a.Time != null)
                              && (a.Distance + 123 > 0)
                              && (a.CurrentLoad + 123 > 0)
                              && a.Origin != null
                              && a.Destination != null
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}