// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for MapPointsTest and is intended
    ///to contain all MapPointsTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("MapPoints Repository Tests")]
    [Category("MapPoints Repository Tests")]
    internal class MapPointsTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `MapPoints`")]
        [Order(0)]
        public void MapPoints_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.MapPoints>(Session)
            .CheckProperty(p => p.Lat, 222.222f)
            .CheckProperty(p => p.Long, 222.222f)
            .CheckProperty(p => p.Title, "MapPoints_Title")
            .CheckProperty(p => p.Type, "MapPoints_Type")
            .CheckProperty(p => p.Icon, "MapPoints_Icon")
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `MapPoints`")]
        [Order(1)]
        public void MapPoints_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.MapPoints> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.MapPoints>(
                              a => true
                              && (a.Lat + 123 > 0)
                              && (a.Long + 123 > 0)
                              && (a.Title != string.Empty && a.Title != null)
                              && (a.Type != string.Empty && a.Type != null)
                              && (a.Icon != string.Empty && a.Icon != null)
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}