// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for SolutionTest and is intended
    ///to contain all SolutionTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("Solution Repository Tests")]
    [Category("Solution Repository Tests")]
    internal class SolutionTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `Solution`")]
        [Order(0)]
        public void Solution_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _vrpsolution_routes_solution = new DSS3_LogisticsPoolingForUrbanDistribution.BO.Route
            {
                TotalTime = 5242,
                TotalDistance = 4066,
            };
            var _vrpsolution_routes_solution2 = new DSS3_LogisticsPoolingForUrbanDistribution.BO.Route
            {
                TotalTime = 4065,
                TotalDistance = 3478,
            };
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.Solution>(Session)
            .CheckProperty(p => p.TotalTime, 2516)
            .CheckProperty(p => p.TotalDistance, 9407)
            .CheckBag(p => p.Routes, (new List<DSS3_LogisticsPoolingForUrbanDistribution.BO.Route>
            {
                _vrpsolution_routes_solution,
                _vrpsolution_routes_solution2
            }))
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `Solution`")]
        [Order(1)]
        public void Solution_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.Solution> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.Solution>(
                              a => true
                              && (a.TotalTime + 123 > 0)
                              && (a.TotalDistance + 123 > 0)
                              && a.Routes.Any()
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}