// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for StatusEvolutionTest and is intended
    ///to contain all StatusEvolutionTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("StatusEvolution Repository Tests")]
    [Category("StatusEvolution Repository Tests")]
    internal class StatusEvolutionTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `StatusEvolution`")]
        [Order(0)]
        public void StatusEvolution_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _ordersbo_status_orderstatus = new DSS3_LogisticsPoolingForUrbanDistribution.BO.Status
            {
                Code = "Status_Code",
                Description = "Status_Description",
            };
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.StatusEvolution>(Session)
            .CheckProperty(p => p.TimeChanged, now)
            .CheckProperty(p => p.Description, "StatusEvolution_Description")
            .CheckReference(p => p.Status, _ordersbo_status_orderstatus)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `StatusEvolution`")]
        [Order(1)]
        public void StatusEvolution_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.StatusEvolution> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.StatusEvolution>(
                              a => true
                              && a.TimeChanged.GetValueOrDefault().Date <= DateTime.UtcNow.Date
                              && (a.Description != string.Empty && a.Description != null)
                              && a.Status != null
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}