// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests.Common;
using DSS3_LogisticsPoolingForUrbanDistribution.DAL;

namespace DSS3_LogisticsPoolingForUrbanDistribution.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for WarehouseTest and is intended
    ///to contain all WarehouseTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("Warehouse Repository Tests")]
    [Category("Warehouse Repository Tests")]
    internal class WarehouseTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `Warehouse`")]
        [Order(0)]
        public void Warehouse_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _order_geocoordinates_warehouse = new DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoCoordinates
            {
                Latitude = 222.222f,
                Longitude = 222.222f,
            };
            var _order_regionalagentsservice_warehousessupport = new DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgent
            {
                AgencyCode = "RegionalAgent_AgencyCode",
                AgencyDescription = "RegionalAgent_AgencyDescription",
                AgencyAddress = "RegionalAgent_AgencyAddress",
                IsSelected = true,
                Rating = 8544,
            };
            var _order_regionalagentsservice_warehousessupport2 = new DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgent
            {
                AgencyCode = "RegionalAgent_AgencyCode",
                AgencyDescription = "RegionalAgent_AgencyDescription",
                AgencyAddress = "RegionalAgent_AgencyAddress",
                IsSelected = true,
                Rating = 3652,
            };
            new PersistenceSpecification<DSS3_LogisticsPoolingForUrbanDistribution.BO.Warehouse>(Session)
            .CheckProperty(p => p.Description, "Warehouse_Description")
            .CheckProperty(p => p.Title, "Warehouse_Title")
            .CheckProperty(p => p.Address, "Warehouse_Address")
            .CheckProperty(p => p.Telephone, "Warehouse_Telephone")
            .CheckReference(p => p.GeoCoordinates, _order_geocoordinates_warehouse)
            .CheckBag(p => p.RegionalAgentsService, (new List<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgent>
            {
                _order_regionalagentsservice_warehousessupport,
                _order_regionalagentsservice_warehousessupport2
            }))
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `Warehouse`")]
        [Order(1)]
        public void Warehouse_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS3_LogisticsPoolingForUrbanDistribution.BO.Warehouse> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.Warehouse>(
                              a => true
                              && (a.Description != string.Empty && a.Description != null)
                              && (a.Title != string.Empty && a.Title != null)
                              && (a.Address != string.Empty && a.Address != null)
                              && (a.Telephone != string.Empty && a.Telephone != null)
                              && a.GeoCoordinates != null
                              && a.RegionalAgentsService.Any()
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}