// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.UI.Controllers.MasterPage;
using AppCode;
using zAppDev.DotNet.Framework.Data;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Mvc;
using System.ComponentModel.DataAnnotations;
namespace DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage
{
    public class MasterPageViewModel
    {
        public string Title;


        public MasterPageViewModel()
        {
        }


        public virtual void Evict()
        {
            var manager = MiniSessionManager.Instance;
        }

    }


    [OriginalType(typeof(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel))]
    public class MasterPageViewModelDTO : ViewModelDTOBase, IViewModelDTO<DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel>
    {

        [JsonConstructor]
        public MasterPageViewModelDTO() { }
        public MasterPageViewModelDTO(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel original, bool parentIsDirty = false)
        {
            if (original == null) return;
            _runtimeType = original.GetType().FullName;
            Title = original.Title;
        }
        public string Title;
        public  string _runtimeType
        {
            get;
            set;
        }
        public override string _originalTypeClassName => typeof(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel).FullName;

        public DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            return new DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel();
        }
        public DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPage.MasterPageViewModel original)
        {
            if (original == null) return;
            original.Title = Title;
        }
    }



}
