// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using DSS3_LogisticsPoolingForUrbanDistribution.UI.Controllers.Unauthorized;
using AppCode;
using zAppDev.DotNet.Framework.Data;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Mvc;
using System.ComponentModel.DataAnnotations;
using DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.MasterPageSignIn;
using DSS3_LogisticsPoolingForUrbanDistribution.UI.Controllers.MasterPageSignIn;
namespace DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized
{
    public class UnauthorizedViewModel : MasterPageSignInViewModel
    {


        public UnauthorizedViewModel()
        {
        }


        public override void Evict()
        {
            var manager = MiniSessionManager.Instance;
        }

    }


    [OriginalType(typeof(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel))]
    public class UnauthorizedViewModelDTO : MasterPageSignInViewModelDTO, IViewModelDTO<DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel>
    {

        [JsonConstructor]
        public UnauthorizedViewModelDTO() { }
        public UnauthorizedViewModelDTO(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel original, bool parentIsDirty = false)  : base(original)
        {
            if (original == null) return;
            _runtimeType = original.GetType().FullName;
        }
        public new string _runtimeType
        {
            get;
            set;
        }
        public override string _originalTypeClassName => typeof(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel).FullName;

        public new DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            return new DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel();
        }
        new  public DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DSS3_LogisticsPoolingForUrbanDistribution.UI.ViewModels.Unauthorized.UnauthorizedViewModel original)
        {
            if (original == null) return;
            base.Hydrate(original);
        }
    }



}
