// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using DSS3_LogisticsPoolingForUrbanDistribution.Services.DataSeed.DataContracts;

namespace DSS3_LogisticsPoolingForUrbanDistribution.Services
{
    [XmlSerializerFormat]
    [ServiceContract]
    public interface IDataSeedService
    {
        [OperationContract]
        void Orders(DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS[] _orders, string _RequestSourceIp, string _UserName);

        [OperationContract]
        void InitRegionalAgents(string _RequestSourceIp, string _UserName);

        [OperationContract]
        void Change(string _RequestSourceIp, string _UserName);

        [OperationContract]
        void TestGoogleAPI(string _RequestSourceIp, string _UserName);

        [OperationContract]
        void initWarehouse(string _RequestSourceIp, string _UserName);

        [OperationContract]
        System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.Services.DataSeed.DataContracts.OrderWMSDTO> testOrderGenerator(string _RequestSourceIp, string _UserName);

        [OperationContract]
        System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.Services.DataSeed.DataContracts.PubMessageDTO> testReflection(string _RequestSourceIp, string _UserName);

        [OperationContract]
        void TruckPosistions(string _RequestSourceIp, string _UserName);


    }
}