// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using System.ServiceModel.Channels;
using System.Security.Permissions;
using System.Security.Principal;
using NHibernate;
using System.ServiceModel.Activation;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using DSS3_LogisticsPoolingForUrbanDistribution.Services.RA.DataContracts;
using DSS3_LogisticsPoolingForUrbanDistribution.BO;
using AutoMapper;

namespace DSS3_LogisticsPoolingForUrbanDistribution.Services
{
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Required)]
    public class RAService : IRAService
    {
        public RegionalAgentUserDTO GetRA(string _raname, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputraname = _raname;
                var _getRA = GetRAImplementation(inputraname);
                var result = Mapper.Map<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser, RegionalAgentUserDTO>(_getRA);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }
        public OrderWMSDTO GetOrderWMS(int? _id, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputid = _id;
                var _getOrderWMS = GetOrderWMSImplementation(inputid);
                var result = Mapper.Map<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS, OrderWMSDTO>(_getOrderWMS);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }
        public void SaveOrder(OrderWMSDTO _order, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputorder = Mapper.Map<OrderWMSDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>(_order);
                SaveOrderImplementation(inputorder);
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }
        public TruckDriverDTO GetTruckDriver(string _username, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputusername = _username;
                var _getTruckDriver = GetTruckDriverImplementation(inputusername);
                var result = Mapper.Map<DSS3_LogisticsPoolingForUrbanDistribution.BO.TruckDriver, TruckDriverDTO>(_getTruckDriver);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }
        public System.Collections.Generic.List<OrderWMSDTO> GetAllOrderWMS(string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var _getAllOrderWMS = GetAllOrderWMSImplementation();
                var result = Mapper.Map<System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>, System.Collections.Generic.List<OrderWMSDTO>>(_getAllOrderWMS);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }
        public System.Collections.Generic.List<OrderWMSDTO> GetOrderByTruck(string _plateNumber, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputplateNumber = _plateNumber;
                var _getOrderByTruck = GetOrderByTruckImplementation(inputplateNumber);
                var result = Mapper.Map<System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>, System.Collections.Generic.List<OrderWMSDTO>>(_getOrderByTruck);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }
        public System.Collections.Generic.List<OrderWMSDTO> GetOrderByAgency(string _agencyCode, string _RequestSourceIp, string _UserName)
        {
            InitializeMappers();
            try
            {
                var inputagencyCode = _agencyCode;
                var _getOrderByAgency = GetOrderByAgencyImplementation(inputagencyCode);
                var result = Mapper.Map<System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>, System.Collections.Generic.List<OrderWMSDTO>>(_getOrderByAgency);
                return result;
            }
            catch (Exception @exception)
            {
                log4net.LogManager.GetLogger("RA Service").Error(@exception);
                throw;
            }
        }


        private void InitializeMappers()
        {
            Mapper.CreateMap<GeoAreaDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoArea>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoArea, GeoAreaDTO>();
            Mapper.CreateMap<GeoCoordinatesDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoCoordinates>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoCoordinates, GeoCoordinatesDTO>();
            Mapper.CreateMap<OrderWMSDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS, OrderWMSDTO>();
            Mapper.CreateMap<RegionalAgentDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgent>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgent, RegionalAgentDTO>();
            Mapper.CreateMap<RegionalAgentUserDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser, RegionalAgentUserDTO>();
            Mapper.CreateMap<ScheduledRouteTemplateDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate, ScheduledRouteTemplateDTO>();
            Mapper.CreateMap<TruckDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.Truck>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.Truck, TruckDTO>();
            Mapper.CreateMap<TruckDriverDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.TruckDriver>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.TruckDriver, TruckDriverDTO>();
            Mapper.CreateMap<WarehouseDTO, DSS3_LogisticsPoolingForUrbanDistribution.BO.Warehouse>();
            Mapper.CreateMap<DSS3_LogisticsPoolingForUrbanDistribution.BO.Warehouse, WarehouseDTO>();
        }

        public static DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser GetRAImplementation(string raname)
        {
            DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser rauser = new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser>((us) => us.UserName == raname)?.FirstOrDefault();
            return rauser;
        }

        public static DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS GetOrderWMSImplementation(int? id)
        {
            return  new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetById<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>(id);
        }

        public static void SaveOrderImplementation(DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS order)
        {
            new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Save<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>(order);
        }

        public static DSS3_LogisticsPoolingForUrbanDistribution.BO.TruckDriver GetTruckDriverImplementation(string username)
        {
            return new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAsQueryable<DSS3_LogisticsPoolingForUrbanDistribution.BO.TruckDriver>((truck) => truck.UserName == username)?.FirstOrDefault();
        }

        public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS> GetAllOrderWMSImplementation()
        {
            return new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().GetAll<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>();
        }

        public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS> GetOrderByTruckImplementation(string plateNumber)
        {
            return new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>((order) => order.Truck == plateNumber);
        }

        public static System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS> GetOrderByAgencyImplementation(string agencyCode)
        {
            return new DSS3_LogisticsPoolingForUrbanDistribution.DAL.Repository().Get<DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS>((ord) => ord.OrdAgencyCode == agencyCode);
        }


    }
}