// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using zAppDev.DotNet.Framework.Mvc;
using AppCode;
using Identity = zAppDev.DotNet.Framework.Identity;
using zAppDev.DotNet.Framework.Identity;
namespace DSS3_LogisticsPoolingForUrbanDistribution.Web.Code.WebApi
{


    [RoutePrefix("api/KPIService")]
    [WebApiThrottle.EnableThrottling()]
    public class KPIServiceController : BasicApiCtrl
    {

        /// <summary>
        ///
        /// </summary>
        /// <returns>Collection</returns>
        [CustomWebApiActionFilter(LogEnabled = true, AllowPartialResponse = true)]
        [CustomWebApiAuthorize(LogEnabled = true)]

        [Route("GetVolumePerLSP")]
        [HttpGet]
        public System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIService.DataContracts.VolumePerShipperDTO> GetVolumePerLSP(string Name = "")
        {
            var request = ((HttpContextBase)Request.Properties["MS_HttpContext"]).Request;
            var _RequestSourceIp = request.UserHostAddress;
            var _UserName = Identity.IdentityHelper.GetCurrentUserName();
            var result =  (new DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIServiceService()).GetVolumePerLSP(Name,_RequestSourceIp, _UserName);
            return result;
        }

        /// <summary>
        ///
        /// </summary>
        /// <returns>Collection</returns>
        [CustomWebApiActionFilter(LogEnabled = true, AllowPartialResponse = true)]
        [CustomWebApiAuthorize(LogEnabled = true)]

        [Route("GetVolumePerUnit")]
        [HttpGet]
        public System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIService.DataContracts.VolumePerShipperDTO> GetVolumePerUnit(string Name = "")
        {
            var request = ((HttpContextBase)Request.Properties["MS_HttpContext"]).Request;
            var _RequestSourceIp = request.UserHostAddress;
            var _UserName = Identity.IdentityHelper.GetCurrentUserName();
            var result =  (new DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIServiceService()).GetVolumePerUnit(Name,_RequestSourceIp, _UserName);
            return result;
        }

        /// <summary>
        ///
        /// </summary>
        /// <returns>Collection</returns>
        [CustomWebApiActionFilter(LogEnabled = true, AllowPartialResponse = true)]
        [CustomWebApiAuthorize(LogEnabled = true)]

        [Route("CO2PerCarrier")]
        [HttpGet]
        public System.Collections.Generic.List<DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIService.DataContracts.CO2PerCarrierDTO> CO2PerCarrier(string Name = "")
        {
            var request = ((HttpContextBase)Request.Properties["MS_HttpContext"]).Request;
            var _RequestSourceIp = request.UserHostAddress;
            var _UserName = Identity.IdentityHelper.GetCurrentUserName();
            var result =  (new DSS3_LogisticsPoolingForUrbanDistribution.Services.KPIServiceService()).CO2PerCarrier(Name,_RequestSourceIp, _UserName);
            return result;
        }
    }
}
