// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using zAppDev.DotNet.Framework.Data.DAL;
using zAppDev.DotNet.Framework.Workflow;
using zAppDev.DotNet.Framework.Auditing;
using zAppDev.DotNet.Framework.Identity;
using zAppDev.DotNet.Framework.Identity.Model;

namespace DSS3_LogisticsPoolingForUrbanDistribution.DAL
{
    public interface IRepository: ICreateRepository, IIdentityRepository, IAuditingRepository, IDeleteRepository, IRetrieveRepository, IUpdateRepository, IWorkflowRepository
    {
        void DeleteShipment(DSS3_LogisticsPoolingForUrbanDistribution.BO.Shipment shipment, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteShipmentStatus(DSS3_LogisticsPoolingForUrbanDistribution.BO.ShipmentStatus shipmentstatus, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletePoint(DSS3_LogisticsPoolingForUrbanDistribution.BO.Point point, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteDriver(DSS3_LogisticsPoolingForUrbanDistribution.BO.Driver driver, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteShippingOrder(DSS3_LogisticsPoolingForUrbanDistribution.BO.ShippingOrder shippingorder, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteStatusEvolution(DSS3_LogisticsPoolingForUrbanDistribution.BO.StatusEvolution statusevolution, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteVolume(DSS3_LogisticsPoolingForUrbanDistribution.BO.Volume volume, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteItemType(DSS3_LogisticsPoolingForUrbanDistribution.BO.ItemType itemtype, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletePriority(DSS3_LogisticsPoolingForUrbanDistribution.BO.Priority priority, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteStatus(DSS3_LogisticsPoolingForUrbanDistribution.BO.Status status, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteLocation(DSS3_LogisticsPoolingForUrbanDistribution.BO.Location location, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteCoordinates(DSS3_LogisticsPoolingForUrbanDistribution.BO.Coordinates coordinates, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteSupplier(DSS3_LogisticsPoolingForUrbanDistribution.BO.Supplier supplier, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteReason(DSS3_LogisticsPoolingForUrbanDistribution.BO.Reason reason, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteCondition(DSS3_LogisticsPoolingForUrbanDistribution.BO.Condition condition, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteLegVolumeDetails(DSS3_LogisticsPoolingForUrbanDistribution.BO.LegVolumeDetails legvolumedetails, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletePathVolumeDetail(DSS3_LogisticsPoolingForUrbanDistribution.BO.PathVolumeDetail pathvolumedetail, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteCostSplit(DSS3_LogisticsPoolingForUrbanDistribution.BO.CostSplit costsplit, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteStatusRule(DSS3_LogisticsPoolingForUrbanDistribution.BO.StatusRule statusrule, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteVehicule(DSS3_LogisticsPoolingForUrbanDistribution.BO.Vehicule vehicule, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteDistanceCosts(DSS3_LogisticsPoolingForUrbanDistribution.BO.DistanceCosts distancecosts, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteTimeCosts(DSS3_LogisticsPoolingForUrbanDistribution.BO.TimeCosts timecosts, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteOwnershipCost(DSS3_LogisticsPoolingForUrbanDistribution.BO.OwnershipCost ownershipcost, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletePropulsionTypeCost(DSS3_LogisticsPoolingForUrbanDistribution.BO.PropulsionTypeCost propulsiontypecost, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteOilType(DSS3_LogisticsPoolingForUrbanDistribution.BO.OilType oiltype, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAmortizationType(DSS3_LogisticsPoolingForUrbanDistribution.BO.AmortizationType amortizationtype, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteVolumePerShipper(DSS3_LogisticsPoolingForUrbanDistribution.BO.VolumePerShipper volumepershipper, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteCO2PerCarrier(DSS3_LogisticsPoolingForUrbanDistribution.BO.CO2PerCarrier co2percarrier, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteCustomVolume(DSS3_LogisticsPoolingForUrbanDistribution.BO.CustomVolume customvolume, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteVolumeComponent(DSS3_LogisticsPoolingForUrbanDistribution.BO.VolumeComponent volumecomponent, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteVolumeComposition(DSS3_LogisticsPoolingForUrbanDistribution.BO.VolumeComposition volumecomposition, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteSolution(DSS3_LogisticsPoolingForUrbanDistribution.BO.Solution solution, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteRoute(DSS3_LogisticsPoolingForUrbanDistribution.BO.Route route, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteActivity(DSS3_LogisticsPoolingForUrbanDistribution.BO.Activity activity, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteTblZslNormalisationSuggestion(DSS3_LogisticsPoolingForUrbanDistribution.BO.TblZslNormalisationSuggestion tblzslnormalisationsuggestion, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslBookingType(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslBookingType tblzslbookingtype, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslCarrier(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslCarrier tblzslcarrier, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslCustomer(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslCustomer tblzslcustomer, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslDeliveryStatus(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslDeliveryStatus tblzsldeliverystatus, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslPlatformBookingOrder(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslPlatformBookingOrder tblzslplatformbookingorder, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslRoute(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslRoute tblzslroute, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslTransportDetail(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslTransportDetail tblzsltransportdetail, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslTransportEvent(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslTransportEvent tblzsltransportevent, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslTransportExecutionPlan(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslTransportExecutionPlan tblzsltransportexecutionplan, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslTransportOrder(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslTransportOrder tblzsltransportorder, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeletetblZslWorker(DSS3_LogisticsPoolingForUrbanDistribution.BO.tblZslWorker tblzslworker, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteComment(DSS3_LogisticsPoolingForUrbanDistribution.BO.Comment comment, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteOrderStatistics(DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderStatistics orderstatistics, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteLSP(DSS3_LogisticsPoolingForUrbanDistribution.BO.LSP lsp, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteLSPUser(DSS3_LogisticsPoolingForUrbanDistribution.BO.LSPUser lspuser, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteOrderWMS(DSS3_LogisticsPoolingForUrbanDistribution.BO.OrderWMS orderwms, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteWarehouse(DSS3_LogisticsPoolingForUrbanDistribution.BO.Warehouse warehouse, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteProofOfDelivery(DSS3_LogisticsPoolingForUrbanDistribution.BO.ProofOfDelivery proofofdelivery, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteRegionalAgent(DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgent regionalagent, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteRegionalAgentUser(DSS3_LogisticsPoolingForUrbanDistribution.BO.RegionalAgentUser regionalagentuser, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteGeoCoordinates(DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoCoordinates geocoordinates, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteGeoArea(DSS3_LogisticsPoolingForUrbanDistribution.BO.GeoArea geoarea, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteTruckDriver(DSS3_LogisticsPoolingForUrbanDistribution.BO.TruckDriver truckdriver, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteTruck(DSS3_LogisticsPoolingForUrbanDistribution.BO.Truck truck, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteOrdersPerMonth(DSS3_LogisticsPoolingForUrbanDistribution.BO.OrdersPerMonth orderspermonth, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteChartWorkaround(DSS3_LogisticsPoolingForUrbanDistribution.BO.ChartWorkaround chartworkaround, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteMapPoints(DSS3_LogisticsPoolingForUrbanDistribution.BO.MapPoints mappoints, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAVGTime(DSS3_LogisticsPoolingForUrbanDistribution.BO.AVGTime avgtime, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteStatePeriod(DSS3_LogisticsPoolingForUrbanDistribution.BO.StatePeriod stateperiod, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteScheduledRouteTemplate(DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRouteTemplate scheduledroutetemplate, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteScheduledRoute(DSS3_LogisticsPoolingForUrbanDistribution.BO.ScheduledRoute scheduledroute, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteWorkContract(DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkContract workcontract, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationUserAction(zAppDev.DotNet.Framework.Identity.Model.ApplicationUserAction applicationuseraction, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationUserExternalProfile(zAppDev.DotNet.Framework.Identity.Model.ApplicationUserExternalProfile applicationuserexternalprofile, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationSetting(zAppDev.DotNet.Framework.Identity.Model.ApplicationSetting applicationsetting, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationUser(zAppDev.DotNet.Framework.Identity.Model.ApplicationUser applicationuser, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationRole(zAppDev.DotNet.Framework.Identity.Model.ApplicationRole applicationrole, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationOperation(zAppDev.DotNet.Framework.Identity.Model.ApplicationOperation applicationoperation, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationPermission(zAppDev.DotNet.Framework.Identity.Model.ApplicationPermission applicationpermission, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationClient(zAppDev.DotNet.Framework.Identity.Model.ApplicationClient applicationclient, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationUserLogin(zAppDev.DotNet.Framework.Identity.Model.ApplicationUserLogin applicationuserlogin, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationUserClaim(zAppDev.DotNet.Framework.Identity.Model.ApplicationUserClaim applicationuserclaim, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteProfileSetting(zAppDev.DotNet.Framework.Identity.Model.ProfileSetting profilesetting, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteProfile(zAppDev.DotNet.Framework.Identity.Model.Profile profile, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationLanguage(zAppDev.DotNet.Framework.Identity.Model.ApplicationLanguage applicationlanguage, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteDateTimeFormat(zAppDev.DotNet.Framework.Identity.Model.DateTimeFormat datetimeformat, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteApplicationTheme(zAppDev.DotNet.Framework.Identity.Model.ApplicationTheme applicationtheme, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteFileData(DSS3_LogisticsPoolingForUrbanDistribution.BO.FileData filedata, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAuditEntityConfiguration(zAppDev.DotNet.Framework.Auditing.Model.AuditEntityConfiguration auditentityconfiguration, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAuditPropertyConfiguration(zAppDev.DotNet.Framework.Auditing.Model.AuditPropertyConfiguration auditpropertyconfiguration, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAuditLogEntry(zAppDev.DotNet.Framework.Auditing.Model.AuditLogEntry auditlogentry, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAuditLogEntryType(zAppDev.DotNet.Framework.Auditing.Model.AuditLogEntryType auditlogentrytype, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteAuditLogPropertyActionType(zAppDev.DotNet.Framework.Auditing.Model.AuditLogPropertyActionType auditlogpropertyactiontype, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteWorkflowContextBase(zAppDev.DotNet.Framework.Workflow.WorkflowContextBase workflowcontextbase, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteWorkflowSchedule(zAppDev.DotNet.Framework.Workflow.WorkflowSchedule workflowschedule, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        void DeleteWorkflowSockContext(DSS3_LogisticsPoolingForUrbanDistribution.BO.WorkflowSockContext workflowsockcontext, bool doNotCallDeleteForThis = false, bool isCascaded = false, object calledBy = null);
        List<T> Get<T>(Expression<Func<T, bool>> predicate, bool cacheQuery = true);
        List<T> Get<T>(Expression<Func<T, bool>> predicate,
                       int startRowIndex,
                       int pageSize,
                       Dictionary<Expression<Func<T, object>>, bool> orderBy,
                       out int totalRecords, bool cacheQuery = true);

        List<T> GetAll<T>(bool cacheQuery = true);
        List<T> GetAll<T>(int startRowIndex, int pageSize, out int totalRecords, bool cacheQuery = true);
    }
}
